name: parkinsondetetion
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  permission_handler: ^12.0.0+1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  cloud_functions: ^5.4.0
  responsive_builder: ^0.7.0
  sensors_plus: ^3.0.3
  fftea: ^1.5.0+1
  fl_chart: ^0.64.0
  tflite_flutter: ^0.11.0



dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true

  assets:
    - assets/tapping_model.tflite
