/// Schema describing all questionnaire fields.
/// Each map entry defines validation rules and display information.

const List<Map<String, dynamic>> questionnaireSchema = [
  // --------------------- Demographics ---------------------
  {
    'id': 'demographics.age',
    'section': 'Demographics',
    'type': 'integer',
    'label': 'How old are you?',
    'options': [],
    'validation': {'min': 0, 'max': 120, 'required': true},
  },
  {
    'id': 'demographics.gender',
    'section': 'Demographics',
    'type': 'select',
    'label': 'What is your gender?',
    'options': [
      {'value': 'male', 'label': 'Male'},
      {'value': 'female', 'label': 'Female'},
      {'value': 'other', 'label': 'Other'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'demographics.yearsSinceDiagnosis',
    'section': 'Demographics',
    'type': 'integer',
    'label': 'Years since Parkinson\'s diagnosis',
    'options': [],
    'validation': {'min': 0, 'max': 60, 'required': true},
  },
  {
    'id': 'demographics.educationLevel',
    'section': 'Demographics',
    'type': 'select',
    'label': 'Highest education level completed',
    'options': [
      {'value': 'high_school', 'label': 'High School'},
      {'value': 'college', 'label': 'College'},
      {'value': 'graduate', 'label': 'Graduate'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'demographics.employmentStatus',
    'section': 'Demographics',
    'type': 'select',
    'label': 'Current employment status',
    'options': [
      {'value': 'employed', 'label': 'Employed'},
      {'value': 'unemployed', 'label': 'Unemployed'},
      {'value': 'retired', 'label': 'Retired'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'demographics.handedness',
    'section': 'Demographics',
    'type': 'select',
    'label': 'Which hand is dominant?',
    'options': [
      {'value': 'right', 'label': 'Right'},
      {'value': 'left', 'label': 'Left'},
      {'value': 'both', 'label': 'Ambidextrous'},
    ],
    'validation': {'required': true},
  },

  // ------------------------- Motor ------------------------
  {
    'id': 'motor.walkingDifficulty',
    'section': 'Motor',
    'type': 'integer',
    'label': 'Rate your walking difficulty (0 none – 4 severe)',
    'options': [],
    'validation': {'min': 0, 'max': 4, 'required': true},
  },
  {
    'id': 'motor.tremorSeverity',
    'section': 'Motor',
    'type': 'integer',
    'label': 'Rate your tremor severity (0 none – 4 severe)',
    'options': [],
    'validation': {'min': 0, 'max': 4, 'required': true},
  },
  {
    'id': 'motor.rigiditySeverity',
    'section': 'Motor',
    'type': 'integer',
    'label': 'Rate muscle rigidity (0 none – 4 severe)',
    'options': [],
    'validation': {'min': 0, 'max': 4, 'required': true},
  },
  {
    'id': 'motor.bradykinesiaSeverity',
    'section': 'Motor',
    'type': 'integer',
    'label': 'Rate slowness of movement (0 none – 4 severe)',
    'options': [],
    'validation': {'min': 0, 'max': 4, 'required': true},
  },
  {
    'id': 'motor.postureInstability',
    'section': 'Motor',
    'type': 'integer',
    'label': 'Rate postural instability (0 none – 4 severe)',
    'options': [],
    'validation': {'min': 0, 'max': 4, 'required': true},
  },
  {
    'id': 'motor.freezingGait',
    'section': 'Motor',
    'type': 'integer',
    'label': 'Rate freezing of gait episodes (0 none – 4 severe)',
    'options': [],
    'validation': {'min': 0, 'max': 4, 'required': true},
  },
  {
    'id': 'motor.dyskinesiaSeverity',
    'section': 'Motor',
    'type': 'integer',
    'label': 'Rate dyskinesia severity (0 none – 4 severe)',
    'options': [],
    'validation': {'min': 0, 'max': 4, 'required': true},
  },

  // ----------------------- Medication ---------------------
  {
    'id': 'medication.levoDose',
    'section': 'Medication',
    'type': 'number',
    'label': 'Daily levodopa dosage (mg)',
    'options': [],
    'validation': {'min': 0, 'max': 2000, 'required': true},
  },
  {
    'id': 'medication.otherMeds',
    'section': 'Medication',
    'type': 'boolean',
    'label': 'Do you take other Parkinson\'s medications?',
    'options': [
      {'value': true, 'label': 'Yes'},
      {'value': false, 'label': 'No'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'medication.listOtherMeds',
    'section': 'Medication',
    'type': 'string',
    'label': 'List other medications',
    'options': [],
    'validation': {'required': true},
    'dependsOn': {'questionId': 'medication.otherMeds', 'value': true},
  },
  {
    'id': 'medication.sideEffects',
    'section': 'Medication',
    'type': 'boolean',
    'label': 'Do you experience medication side effects?',
    'options': [
      {'value': true, 'label': 'Yes'},
      {'value': false, 'label': 'No'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'medication.onOffFluctuations',
    'section': 'Medication',
    'type': 'boolean',
    'label': 'Do you have on/off fluctuations?',
    'options': [
      {'value': true, 'label': 'Yes'},
      {'value': false, 'label': 'No'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'medication.medicationAdherence',
    'section': 'Medication',
    'type': 'integer',
    'label': 'Medication adherence (0% – 100%)',
    'options': [],
    'validation': {'min': 0, 'max': 100, 'required': true},
  },
  {
    'id': 'medication.lastDoseTime',
    'section': 'Medication',
    'type': 'string',
    'label': 'Time of last dose (hh:mm)',
    'options': [],
    'validation': {'required': true},
  },

  // ----------------------- NonMotor -----------------------
  {
    'id': 'nonmotor.sleepProblems',
    'section': 'NonMotor',
    'type': 'boolean',
    'label': 'Have you had trouble sleeping recently?',
    'options': [
      {'value': true, 'label': 'Yes'},
      {'value': false, 'label': 'No'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'nonmotor.constipation',
    'section': 'NonMotor',
    'type': 'boolean',
    'label': 'Do you suffer from constipation?',
    'options': [
      {'value': true, 'label': 'Yes'},
      {'value': false, 'label': 'No'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'nonmotor.depressionSeverity',
    'section': 'NonMotor',
    'type': 'integer',
    'label': 'How depressed do you feel on average (0 none – 10 severe)?',
    'options': [],
    'validation': {'min': 0, 'max': 10, 'required': true},
  },
  {
    'id': 'nonmotor.anxietySeverity',
    'section': 'NonMotor',
    'type': 'integer',
    'label': 'How anxious do you feel on average (0 none – 10 very)?',
    'options': [],
    'validation': {'min': 0, 'max': 10, 'required': true},
  },
  {
    'id': 'nonmotor.hallucinations',
    'section': 'NonMotor',
    'type': 'boolean',
    'label': 'Have you experienced hallucinations?',
    'options': [
      {'value': true, 'label': 'Yes'},
      {'value': false, 'label': 'No'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'nonmotor.fatigueSeverity',
    'section': 'NonMotor',
    'type': 'integer',
    'label': 'Rate your fatigue level (0 none – 10 extreme)',
    'options': [],
    'validation': {'min': 0, 'max': 10, 'required': true},
  },
  {
    'id': 'nonmotor.cognitiveImpairment',
    'section': 'NonMotor',
    'type': 'boolean',
    'label': 'Do you have noticeable memory problems?',
    'options': [
      {'value': true, 'label': 'Yes'},
      {'value': false, 'label': 'No'},
    ],
    'validation': {'required': true},
  },

  // -------------------------- ADLs ------------------------
  {
    'id': 'adls.dressing',
    'section': 'ADLs',
    'type': 'integer',
    'label': 'Need help dressing? (0 none – 4 cannot)',
    'options': [],
    'validation': {'min': 0, 'max': 4, 'required': true},
  },
  {
    'id': 'adls.eating',
    'section': 'ADLs',
    'type': 'integer',
    'label': 'Need help eating? (0 none – 4 cannot)',
    'options': [],
    'validation': {'min': 0, 'max': 4, 'required': true},
  },
  {
    'id': 'adls.bathing',
    'section': 'ADLs',
    'type': 'integer',
    'label': 'Need help bathing? (0 none – 4 cannot)',
    'options': [],
    'validation': {'min': 0, 'max': 4, 'required': true},
  },
  {
    'id': 'adls.toileting',
    'section': 'ADLs',
    'type': 'integer',
    'label': 'Need help using the toilet? (0 none – 4 cannot)',
    'options': [],
    'validation': {'min': 0, 'max': 4, 'required': true},
  },
  {
    'id': 'adls.handwritingDifficulty',
    'section': 'ADLs',
    'type': 'integer',
    'label': 'Rate handwriting difficulty (0 none – 4 cannot)',
    'options': [],
    'validation': {'min': 0, 'max': 4, 'required': true},
  },
  {
    'id': 'adls.speechDifficulty',
    'section': 'ADLs',
    'type': 'integer',
    'label': 'Rate speech difficulty (0 none – 4 severe)',
    'options': [],
    'validation': {'min': 0, 'max': 4, 'required': true},
  },
  {
    'id': 'adls.turningInBed',
    'section': 'ADLs',
    'type': 'integer',
    'label': 'Difficulty turning in bed (0 none – 4 cannot)',
    'options': [],
    'validation': {'min': 0, 'max': 4, 'required': true},
  },

  // -------------------------- QoL -------------------------
  {
    'id': 'qol.socialLife',
    'section': 'QoL',
    'type': 'select',
    'label': 'How satisfied are you with your social life?',
    'options': [
      {'value': 'satisfied', 'label': 'Satisfied'},
      {'value': 'neutral', 'label': 'Neutral'},
      {'value': 'dissatisfied', 'label': 'Dissatisfied'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'qol.painLevel',
    'section': 'QoL',
    'type': 'integer',
    'label': 'How severe is your pain on average (0 none – 10 worst)?',
    'options': [],
    'validation': {'min': 0, 'max': 10, 'required': true},
  },
  {
    'id': 'qol.mobilitySatisfaction',
    'section': 'QoL',
    'type': 'select',
    'label': 'Are you satisfied with your mobility?',
    'options': [
      {'value': 'satisfied', 'label': 'Satisfied'},
      {'value': 'neutral', 'label': 'Neutral'},
      {'value': 'dissatisfied', 'label': 'Dissatisfied'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'qol.emotionalWellBeing',
    'section': 'QoL',
    'type': 'integer',
    'label': 'Rate your emotional well-being (0 good – 10 poor)',
    'options': [],
    'validation': {'min': 0, 'max': 10, 'required': true},
  },
  {
    'id': 'qol.stigma',
    'section': 'QoL',
    'type': 'integer',
    'label': 'How much stigma do you feel (0 none – 10 high)?',
    'options': [],
    'validation': {'min': 0, 'max': 10, 'required': true},
  },
  {
    'id': 'qol.communicationDifficulty',
    'section': 'QoL',
    'type': 'integer',
    'label': 'Difficulty communicating (0 none – 10 severe)',
    'options': [],
    'validation': {'min': 0, 'max': 10, 'required': true},
  },

  // ------------------- PhysicalActivity ------------------
  {
    'id': 'physicalActivity.minutesPerWeek',
    'section': 'PhysicalActivity',
    'type': 'integer',
    'label': 'How many minutes do you exercise per week?',
    'options': [],
    'validation': {'min': 0, 'max': 1000, 'required': true},
  },
  {
    'id': 'physicalActivity.fallsLastMonth',
    'section': 'PhysicalActivity',
    'type': 'integer',
    'label': 'How many falls have you had in the last month?',
    'options': [],
    'validation': {'min': 0, 'max': 50, 'required': true},
  },
  {
    'id': 'physicalActivity.exerciseType',
    'section': 'PhysicalActivity',
    'type': 'string',
    'label': 'Preferred type of exercise',
    'options': [],
    'validation': {'required': true},
  },
  {
    'id': 'physicalActivity.useWalkingAid',
    'section': 'PhysicalActivity',
    'type': 'boolean',
    'label': 'Do you use a walking aid?',
    'options': [
      {'value': true, 'label': 'Yes'},
      {'value': false, 'label': 'No'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'physicalActivity.balanceProblems',
    'section': 'PhysicalActivity',
    'type': 'integer',
    'label': 'Rate your balance problems (0 none – 4 severe)',
    'options': [],
    'validation': {'min': 0, 'max': 4, 'required': true},
  },
  {
    'id': 'physicalActivity.fatigueAfterExercise',
    'section': 'PhysicalActivity',
    'type': 'integer',
    'label': 'Fatigue after exercise (0 none – 10 extreme)',
    'options': [],
    'validation': {'min': 0, 'max': 10, 'required': true},
  },

  // ----------------------- Nutrition ----------------------
  {
    'id': 'nutrition.appetite',
    'section': 'Nutrition',
    'type': 'select',
    'label': 'How is your appetite?',
    'options': [
      {'value': 'good', 'label': 'Good'},
      {'value': 'fair', 'label': 'Fair'},
      {'value': 'poor', 'label': 'Poor'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'nutrition.weightChange',
    'section': 'Nutrition',
    'type': 'number',
    'label': 'Weight change in the last month (kg)',
    'options': [],
    'validation': {'min': -20, 'max': 20, 'required': true},
  },
  {
    'id': 'nutrition.fluidIntakeCups',
    'section': 'Nutrition',
    'type': 'integer',
    'label': 'How many cups of fluid do you drink daily?',
    'options': [],
    'validation': {'min': 0, 'max': 20, 'required': true},
  },
  {
    'id': 'nutrition.dietarySupplements',
    'section': 'Nutrition',
    'type': 'boolean',
    'label': 'Do you take dietary supplements?',
    'options': [
      {'value': true, 'label': 'Yes'},
      {'value': false, 'label': 'No'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'nutrition.difficultySwallowing',
    'section': 'Nutrition',
    'type': 'boolean',
    'label': 'Difficulty swallowing food?',
    'options': [
      {'value': true, 'label': 'Yes'},
      {'value': false, 'label': 'No'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'nutrition.nauseaFrequency',
    'section': 'Nutrition',
    'type': 'integer',
    'label': 'How often do you feel nauseous? (0 never – 10 always)',
    'options': [],
    'validation': {'min': 0, 'max': 10, 'required': true},
  },

  // ------------------------- Safety -----------------------
  {
    'id': 'safety.driving',
    'section': 'Safety',
    'type': 'boolean',
    'label': 'Do you still drive regularly?',
    'options': [
      {'value': true, 'label': 'Yes'},
      {'value': false, 'label': 'No'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'safety.homeFalls',
    'section': 'Safety',
    'type': 'integer',
    'label': 'Number of falls at home in the last year',
    'options': [],
    'validation': {'min': 0, 'max': 100, 'required': true},
  },
  {
    'id': 'safety.smokeDetector',
    'section': 'Safety',
    'type': 'boolean',
    'label': 'Is there a working smoke detector at home?',
    'options': [
      {'value': true, 'label': 'Yes'},
      {'value': false, 'label': 'No'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'safety.livingAlone',
    'section': 'Safety',
    'type': 'boolean',
    'label': 'Do you live alone?',
    'options': [
      {'value': true, 'label': 'Yes'},
      {'value': false, 'label': 'No'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'safety.medicationMisuse',
    'section': 'Safety',
    'type': 'boolean',
    'label': 'Have you accidentally taken wrong medication?',
    'options': [
      {'value': true, 'label': 'Yes'},
      {'value': false, 'label': 'No'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'safety.emergencyContact',
    'section': 'Safety',
    'type': 'string',
    'label': 'Emergency contact phone number',
    'options': [],
    'validation': {'required': true},
  },

  // ---------------------- Psychosocial --------------------
  {
    'id': 'psychosocial.support',
    'section': 'Psychosocial',
    'type': 'select',
    'label': 'Do you have adequate social support?',
    'options': [
      {'value': 'yes', 'label': 'Yes'},
      {'value': 'no', 'label': 'No'},
      {'value': 'unsure', 'label': 'Unsure'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'psychosocial.anxietyScore',
    'section': 'Psychosocial',
    'type': 'integer',
    'label': 'Anxiety level (0 none – 10 very)',
    'options': [],
    'validation': {'min': 0, 'max': 10, 'required': true},
  },
  {
    'id': 'psychosocial.depressionScore',
    'section': 'Psychosocial',
    'type': 'integer',
    'label': 'Depression level (0 none – 10 very)',
    'options': [],
    'validation': {'min': 0, 'max': 10, 'required': true},
  },
  {
    'id': 'psychosocial.caregiverBurden',
    'section': 'Psychosocial',
    'type': 'integer',
    'label': 'Caregiver burden (0 none – 10 extreme)',
    'options': [],
    'validation': {'min': 0, 'max': 10, 'required': true},
  },
  {
    'id': 'psychosocial.financialStress',
    'section': 'Psychosocial',
    'type': 'integer',
    'label': 'Financial stress level (0 none – 10 extreme)',
    'options': [],
    'validation': {'min': 0, 'max': 10, 'required': true},
  },
  {
    'id': 'psychosocial.supportGroups',
    'section': 'Psychosocial',
    'type': 'boolean',
    'label': 'Do you attend support groups?',
    'options': [
      {'value': true, 'label': 'Yes'},
      {'value': false, 'label': 'No'},
    ],
    'validation': {'required': true},
  },
  {
    'id': 'psychosocial.mentalHealthTherapy',
    'section': 'Psychosocial',
    'type': 'boolean',
    'label': 'Are you receiving mental health therapy?',
    'options': [
      {'value': true, 'label': 'Yes'},
      {'value': false, 'label': 'No'},
    ],
    'validation': {'required': true},
  },
];