/// English presentation text keyed by the stable questionnaire field IDs.
/// The Greek clinical source text remains unchanged in the schema.
const questionnaireEnglishLabels = <String, String>{
  'W': 'What is your sex?',
  'X': 'What is your age?',
  'Y': 'How many years of education have you completed?',
  'Z': 'Are you right-handed or left-handed?',
  'A1': 'Do you have tremor in your upper or lower limbs?',
  'A1_side': 'On which side does the tremor occur?',
  'AA': 'Can you write and drink coffee?',
  'A2': 'Do you have bradykinesia?',
  'A3': 'Do you have rigidity?',
  'RBD_study': 'Have you had a sleep study for REM sleep behaviour disorder (RBD)?',
  'RBD_study_positive': 'Did the sleep study show RBD?',
  'RBD_q': 'Do you have symptoms of REM sleep disturbance, such as vivid dreams or movements?',
  'Memory_Disorder': 'Do you have memory problems?',
  'Urgent_Urination': 'Do you experience an urgent need to urinate?',
  'Execute_Disorder': 'Do you have difficulty planning or completing familiar tasks?',
  'Language_Disorder': 'Do you have language or speech difficulties?',
  'Behavior_Change': 'Have you noticed changes in your behaviour?',
  'Dysarthria': 'Do you have dysarthria?',
  'Dysphagia': 'Do you have difficulty swallowing?',
  'Limb_Weakness': 'Do you have weakness in your upper or lower limbs?',
  'Atrophy': 'Have you noticed muscle wasting in your upper or lower limbs?',
  'Instability': 'Do you experience instability or problems with balance?',
  'Falls': 'Have you fallen recently?',
  'A16': 'Do you make sudden movements or jerks when lying down?',
  'A17': 'Do you have abnormal posturing in your upper or lower limbs?',
  'B': 'Is there a family history of neurological or psychiatric illness?',
  'B1': 'Is there a family history of parkinsonism?',
  'B2': 'Is there a family history of dementia?',
  'B3': 'Is there a family history of psychiatric illness?',
  'G': 'Are you currently taking medication?',
  'G1a': 'Are you taking dopamine agonists?',
  'G1aI': 'How well do you respond to dopamine agonists?',
  'G1b': 'Are you taking levodopa?',
  'G1g': 'Are you taking MAO inhibitors?',
  'G1d': 'Are you taking COMT inhibitors?',
  'G1e': 'Are you taking cholinesterase inhibitors?',
  'G1st': 'Are you taking NMDA antagonists?',
  'G1h': 'Are you taking antidepressants?',
  'G1u': 'Are you taking antipsychotic or neuroleptic medication?',
  'D': 'Have you undergone any additional clinical investigations?',
  'D1a_done': 'Have you had a brain MRI?',
  'D1a': 'What was the brain MRI result?',
  'D1b_done': 'Have you had an MRI of the cervical spine?',
  'D1b': 'What was the cervical spine MRI result?',
  'D1g_done': 'Have you had an MRI of the thoracic spine?',
  'D1g': 'What was the thoracic spine MRI result?',
  'D1d_done': 'Have you had an MRI of the lumbar spine?',
  'D1d': 'What was the lumbar spine MRI result?',
  'D1z_done': 'Have you had a DaTSCAN?',
  'D1z': 'What was the DaTSCAN result?',
  'D1h_done': 'Have you had an HMPAO scan?',
  'D1h': 'What was the HMPAO scan result?',
  'D1u_done': 'Have you had an MIBG scan?',
  'D1u': 'What was the MIBG scan result?',
  'D1k_done': 'Have you had an autonomic nervous system study?',
  'D1k': 'What was the autonomic nervous system study result?',
  'D1l_done': 'Have you had a sleep study?',
  'D1l': 'What was the sleep study result?',
  'D1l4': 'Do you have restless sleep, such as kicking or falling out of bed?',
  'D1m_done': 'Have you had blood tests?',
  'D1m': 'Which blood tests were performed?',
  'D1n_done': 'Have you had genetic or molecular testing?',
  'D1n': 'What was the genetic or molecular test result?',
  'D1j_done': 'Have you had a lumbar puncture?',
  'D1j': 'What was the lumbar puncture result?',
  'D1o_done': 'Have you had electromyography or nerve-conduction studies (EMG/NCS)?',
  'D1o': 'What was the EMG/NCS result?',
  'D1p_done': 'Have you had a neuropsychological assessment?',
  'D1p': 'What was the neuropsychological assessment result?',
  'D1p3i': 'Are you basically satisfied with your life?',
  'D1p3ii': 'Have you dropped many of your activities and interests?',
  'D1p3iii': 'Do you feel that your life is empty?',
  'D1p3iv': 'Do you often get bored?',
  'D1p3v': 'Are you in good spirits most of the time?',
  'D1p3vi': 'Are you afraid that something bad is going to happen to you?',
  'D1p3vii': 'Do you feel happy most of the time?',
  'D1p3viii': 'Do you often feel helpless?',
  'D1p3ix': 'Do you prefer to stay at home rather than go out and do new things?',
  'D1p3x': 'Do you feel you have more memory problems than most people?',
  'D1p3xi': 'Do you think it is wonderful to be alive?',
  'D1p3xii': 'Do you feel worthless in your current situation?',
  'D1p3xiii': 'Do you feel full of energy?',
  'D1p3xiv': 'Do you feel that your situation is hopeless?',
  'D1p3xv': 'Do you think that most people are better off than you are?',
  'D1p4i': 'Compulsive gambling behaviour',
  'D1p4ii': 'Compulsive sexual behaviour',
  'D1p4iii': 'Compulsive buying behaviour',
  'D1p4iv': 'Compulsive eating behaviour',
  'D1p4v': 'Compulsive involvement in hobbies',
  'D1p4vi': 'Compulsive involvement in repetitive simple activities',
  'D1p4vii': 'Compulsive walking or driving',
  'D1p4viii': 'Compulsive use of medication',
  'D1p5i': 'Do you sometimes have very vivid dreams?',
  'D1p5ii': 'Do your dreams have aggressive or violent content?',
  'D1p5iii': 'Does the content of your dreams generally match your behaviour during the night?',
  'D1p5iv': 'Are you aware that your arms or legs move while you sleep?',
  'D1p5v': 'Have you unintentionally hit your partner while sleeping?',
  'D1p5via': 'Do you shout, speak, or laugh loudly while sleeping?',
  'D1p5vib': 'Do you make sudden movements while sleeping?',
  'D1p5vic': 'Do you make gestures or complex movements while sleeping, such as waving or falling out of bed?',
  'D1p5vid': 'Do you knock objects off the bedside table while sleeping?',
  'D1p5vii': 'Do your movements wake you or other people?',
  'D1p5viii': 'When you wake, do you usually remember your dreams well?',
  'D1p5ix': 'Is your sleep often disturbed?',
  'D1p5x': 'Do you have, or have you had, any of the following nervous-system conditions?',
  'D1p6i': 'During the past month, have you had difficulty swallowing or choked?',
  'D1p6ii': 'During the past month, have you experienced drooling?',
  'D1p6iii': 'During the past month, has food become stuck in your throat?',
  'D1p6iv': 'During the past month, have you felt full very quickly?',
  'D1p6v': 'During the past month, have you had constipation?',
  'D1p6vi': 'During the past month, did you have to strain considerably during a bowel movement?',
  'D1p6vii': 'During the past month, did you pass stool unintentionally?',
  'D1p6viii': 'During the past month, did you have difficulty holding your urine?',
  'D1p6ix': 'During the past month, did you experience urinary incontinence?',
  'D1p6x': 'During the past month, did you feel that your bladder had not emptied completely after urinating?',
  'D1p6xi': 'During the past month, was your urine flow reduced?',
  'D1p6xii': 'During the past month, did you need to urinate again within two hours?',
  'D1p6xiii': 'During the past month, did you need to urinate during the night?',
  'D1p6xiv': 'During the past month, when standing up, did you feel light-headed or have difficulty seeing or thinking?',
  'D1p6xv': 'During the past month, did you become dizzy after standing for some time?',
  'D1p6xvi': 'Have you fainted during the past six months?',
  'D1p6xvii': 'During the past month, did you sweat excessively during the day?',
  'D1p6xviii': 'During the past month, did you sweat excessively at night?',
  'D1p6xix': 'During the past month, were you unusually sensitive to bright light?',
  'D1p6xx': 'During the past month, did you have difficulty tolerating cold?',
  'D1p6xxi': 'During the past month, did you have difficulty tolerating heat?',
  'D1p6xxii': 'During the past month, did you have difficulty getting or maintaining an erection?',
  'D1p6xxiii': 'During the past month, did you have difficulty ejaculating?',
  'D1p6xxiv': 'During the past month, did you take medication for erection problems?',
  'D1p6xxv': 'During the past month, did you experience vaginal dryness during intercourse?',
  'D1p6xxvi': 'During the past month, did you have difficulty reaching orgasm?',
};

const questionnaireEnglishOptions = <String, String>{
  'Άνδρας': 'Male', 'Γυναίκα': 'Female',
  'Δεξιοχείρας': 'Right-handed', 'Αριστερόχειρας': 'Left-handed', 'Αμφίχειρας': 'Ambidextrous',
  'Δεξιά': 'Right', 'Αριστερά': 'Left', 'Αμφώ': 'Both',
  'Χωρίς δυσκολία': 'Without difficulty', 'Με δυσκολία': 'With difficulty', 'Καθόλου': 'Not at all',
  'Ναι': 'Yes', 'Όχι': 'No', 'Δεν θυμάμαι': 'I do not remember',
  'Ναι, μετρίως': 'Yes, moderately', 'Ναι, πολύ': 'Yes, greatly',
  'Παθολογικά ευρήματα': 'Abnormal findings', 'Παθολογικα ευρήματα': 'Abnormal findings',
  'Μη παθολογικά ευρήματα': 'No abnormal findings',
  'Παθολογικά ευρήματα για RBD': 'Abnormal findings for RBD',
  'Παθολογικά ευρήματα για Άπνοια‑Υπόπνοια': 'Abnormal findings for sleep apnoea–hypopnoea',
  'Παθολογικά ευρήματα για RBD χωρίς ατονία': 'Abnormal findings for RBD without atonia',
  'Παθολογικά ευρήματα για RLS': 'Abnormal findings for restless legs syndrome',
  'Γενική αίματος': 'Complete blood count', 'Βιοχημικός': 'Biochemistry tests',
  'Δ1μ1+Δ1μ2': 'Complete blood count and biochemistry tests',
  'Ανοσολογικός': 'Immunology tests', 'Παρανεοπλασματικά αντισώματα': 'Paraneoplastic antibodies',
  'Συνδυασμός Δ1μ1–Δ1μ5': 'Combination of the listed blood tests',
  'Εγκεφαλικό': 'Stroke', 'Τραύμα κεφαλής': 'Head injury',
  'Παρκινσονισμός (τρόμος/βραδυκινησία/δυσκαμψία)': 'Parkinsonism (tremor/bradykinesia/rigidity)',
  'Σύνδρομο ανήσυχων ποδιών': 'Restless legs syndrome', 'Ναρκοληψία': 'Narcolepsy',
  'Κατάθλιψη': 'Depression', 'Επιληψία': 'Epilepsy',
  'Φλεγμονώδης νόσος εγκεφάλου': 'Inflammatory brain disease', 'Άλλο': 'Other', 'Κανένα': 'None',
  'Ποτέ': 'Never', 'Μερικές φορές': 'Sometimes', 'Τακτικά': 'Regularly', 'Συχνά': 'Often',
};
