// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQVuSaRCk8YjxKuMGd6Ez18awK4H_AUvQ',
    appId: '1:559294794835:web:ecc8f9a2873f7857148aa6',
    messagingSenderId: '559294794835',
    projectId: 'parkinsondetection-4803f',
    authDomain: 'parkinsondetection-4803f.firebaseapp.com',
    storageBucket: 'parkinsondetection-4803f.firebasestorage.app',
    measurementId: 'G-E725128YK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPsgKPxDKQkHPUUsmhW4JfjU7v2poGP1w',
    appId: '1:559294794835:android:4cea9b2a2a41a586148aa6',
    messagingSenderId: '559294794835',
    projectId: 'parkinsondetection-4803f',
    storageBucket: 'parkinsondetection-4803f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2AisgqBfxkwSV1nEgWAtm2MBQU7L8xS0',
    appId: '1:559294794835:ios:7a5de34ace68d71c148aa6',
    messagingSenderId: '559294794835',
    projectId: 'parkinsondetection-4803f',
    storageBucket: 'parkinsondetection-4803f.firebasestorage.app',
    iosBundleId: 'com.parkinson.detector',
  );
}
