// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4UbnjJf_hbGC4I3SPeRrN9dO6EjlC2pY',
    appId: '1:659877999449:web:7c00b4cc9b4c5e3f0cd248',
    messagingSenderId: '659877999449',
    projectId: 'parkinsonaidetector',
    authDomain: 'parkinsonaidetector.firebaseapp.com',
    databaseURL: 'https://parkinsonaidetector-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'parkinsonaidetector.firebasestorage.app',
    measurementId: 'G-REJNYQ4JPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAINyjaGYmZgJ2lIzyCI7ygd1ChdoKOKsk',
    appId: '1:659877999449:android:3ecfbb2c2156d63b0cd248',
    messagingSenderId: '659877999449',
    projectId: 'parkinsonaidetector',
    databaseURL: 'https://parkinsonaidetector-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'parkinsonaidetector.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZafqEsm1R59b5MSoSHdv2RfpjG4NQY5E',
    appId: '1:659877999449:ios:1e019afa74a6f24d0cd248',
    messagingSenderId: '659877999449',
    projectId: 'parkinsonaidetector',
    databaseURL: 'https://parkinsonaidetector-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'parkinsonaidetector.firebasestorage.app',
    iosBundleId: 'com.terzis.parkinsonaidetector',
  );

}